"""GM (General Manager) AI models — strategic conversation and blueprint storage."""
from __future__ import annotations

import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String, Text, Float
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from packages.db.base import Base


class GMSession(Base):
    """A conversation session with the strategic GM AI."""

    __tablename__ = "gm_sessions"

    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id"), nullable=False, index=True,
    )
    title: Mapped[str] = mapped_column(String(255), default="GM Strategy Session")
    status: Mapped[str] = mapped_column(String(30), default="active")  # active, archived
    machine_phase: Mapped[Optional[str]] = mapped_column(String(40))  # pre_ignition, configuring, first_launch, warmup, scaling, compounding
    message_count: Mapped[int] = mapped_column(Integer, default=0)
    last_message_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    active_blueprint_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), nullable=True,
    )
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)


class GMMessage(Base):
    """A single message in a GM conversation."""

    __tablename__ = "gm_messages"

    session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("gm_sessions.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    role: Mapped[str] = mapped_column(String(20), nullable=False)  # user, gm
    content: Mapped[str] = mapped_column(Text, nullable=False)
    message_type: Mapped[str] = mapped_column(
        String(30), default="conversation",
    )  # conversation, blueprint_presentation, blueprint_revision, execution_report, machine_scan
    blueprint_data: Mapped[Optional[dict]] = mapped_column(JSONB)  # structured blueprint if this message contains one
    machine_state_snapshot: Mapped[Optional[dict]] = mapped_column(JSONB)  # machine state at time of message
    generation_model: Mapped[Optional[str]] = mapped_column(String(60))
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)


class GMBlueprint(Base):
    """A launch blueprint generated by the GM, versioned and trackable."""

    __tablename__ = "gm_blueprints"

    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("gm_sessions.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    version: Mapped[int] = mapped_column(Integer, default=1)
    status: Mapped[str] = mapped_column(
        String(30), default="proposed",
    )  # proposed, approved, executing, completed, superseded

    # The 6 blueprint sections
    account_blueprint: Mapped[Optional[dict]] = mapped_column(JSONB)
    niche_blueprint: Mapped[Optional[dict]] = mapped_column(JSONB)
    identity_blueprint: Mapped[Optional[dict]] = mapped_column(JSONB)
    platform_blueprint: Mapped[Optional[dict]] = mapped_column(JSONB)
    monetization_blueprint: Mapped[Optional[dict]] = mapped_column(JSONB)
    scaling_blueprint: Mapped[Optional[dict]] = mapped_column(JSONB)
    operator_inputs_needed: Mapped[Optional[dict]] = mapped_column(JSONB)
    machine_assessment: Mapped[Optional[dict]] = mapped_column(JSONB)

    # Execution tracking
    execution_progress: Mapped[Optional[dict]] = mapped_column(JSONB)  # {step_key: {status, result, completed_at}}
    approved_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))

    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
