"""System Events — The horizontal integration bus.

Every state transition, job execution, and cross-layer signal emits a SystemEvent.
This is the glue that makes 200+ isolated modules behave as one machine.

Events are lightweight, append-only, and queryable. They allow:
- Control layer to aggregate real-time system state
- Intelligence layer to react to work layer changes
- Governance layer to audit all state transitions
- Recovery layer to detect and respond to failures
- Memory layer to build context over time
"""

import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import Boolean, DateTime, Float, ForeignKey, Index, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from packages.db.base import Base


class SystemEvent(Base):
    """Append-only event log — the nervous system of the operating machine.

    Every meaningful state change emits one of these. Consumers (dashboards,
    intelligence, recovery, memory) read from this table to stay coordinated.
    """

    __tablename__ = "system_events"

    # --- Who / What ---
    organization_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organizations.id"), index=True
    )
    brand_id: Mapped[Optional[uuid.UUID]] = mapped_column(UUID(as_uuid=True), ForeignKey("brands.id"), index=True)

    # --- Event Classification ---
    event_domain: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        index=True,
        comment="Top-level domain: content, publishing, monetization, intelligence, orchestration, governance, recovery",
    )
    event_type: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        index=True,
        comment="Specific event: content.state_changed, job.completed, offer.activated, gate.blocked, etc.",
    )
    event_severity: Mapped[str] = mapped_column(
        String(20), default="info", index=True, comment="info, warning, error, critical"
    )

    # --- Entity Reference ---
    entity_type: Mapped[Optional[str]] = mapped_column(
        String(100),
        index=True,
        comment="The type of object this event is about: content_item, media_job, offer, brand, etc.",
    )
    entity_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), index=True, comment="The specific object ID this event references"
    )

    # --- State Transition ---
    previous_state: Mapped[Optional[str]] = mapped_column(
        String(50), comment="State before this event (null for creation events)"
    )
    new_state: Mapped[Optional[str]] = mapped_column(String(50), comment="State after this event")

    # --- Actor ---
    actor_type: Mapped[str] = mapped_column(
        String(20), default="system", comment="system, human, worker, scheduler, webhook"
    )
    actor_id: Mapped[Optional[str]] = mapped_column(String(255), comment="User ID, worker name, or webhook source")

    # --- Payload ---
    summary: Mapped[str] = mapped_column(
        String(500), nullable=False, comment="Human-readable one-line summary of what happened"
    )
    details: Mapped[Optional[dict]] = mapped_column(
        JSONB, default=dict, comment="Structured payload with event-specific data"
    )

    # --- Correlation ---
    correlation_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), index=True, comment="Groups related events in a workflow (e.g., content creation flow)"
    )
    parent_event_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("system_events.id"), comment="Causal chain: which event triggered this one"
    )

    # --- Consumption ---
    requires_action: Mapped[bool] = mapped_column(
        default=False, comment="True if this event needs operator attention (surfaces in control layer)"
    )
    action_taken: Mapped[bool] = mapped_column(
        default=False, comment="True once an operator or system has addressed this event"
    )
    action_taken_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    action_taken_by: Mapped[Optional[str]] = mapped_column(String(255))

    __table_args__ = (
        Index("ix_system_events_domain_type", "event_domain", "event_type"),
        Index("ix_system_events_requires_action", "requires_action", "action_taken"),
        Index("ix_system_events_created_desc", "created_at"),
        Index("ix_system_events_entity", "entity_type", "entity_id"),
    )


class OperatorAction(Base):
    """Actions available to the operator — surfaced in the control layer.

    These are generated by intelligence, governance, and orchestration layers
    and consumed by the control layer UI. Each action is tied to a specific
    entity and has a clear execution path.
    """

    __tablename__ = "operator_actions"

    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organizations.id"), nullable=False, index=True
    )
    brand_id: Mapped[Optional[uuid.UUID]] = mapped_column(UUID(as_uuid=True), ForeignKey("brands.id"), index=True)

    # --- What to do ---
    action_type: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        index=True,
        comment="approve_content, retry_job, activate_offer, resolve_blocker, review_alert, etc.",
    )
    title: Mapped[str] = mapped_column(
        String(300), nullable=False, comment="Human-readable action title for the control layer"
    )
    description: Mapped[Optional[str]] = mapped_column(
        Text, comment="Detailed explanation of what this action does and why"
    )
    priority: Mapped[str] = mapped_column(
        String(20), default="medium", index=True, comment="critical, high, medium, low"
    )
    category: Mapped[str] = mapped_column(
        String(50), nullable=False, index=True, comment="blocker, approval, opportunity, failure, health, monetization"
    )

    # --- Target ---
    entity_type: Mapped[Optional[str]] = mapped_column(String(100), index=True)
    entity_id: Mapped[Optional[uuid.UUID]] = mapped_column(UUID(as_uuid=True))

    # --- Source ---
    source_event_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("system_events.id"), comment="The system event that generated this action"
    )
    source_module: Mapped[Optional[str]] = mapped_column(
        String(100), comment="Which module generated this: quality_governor, gatekeeper, recovery_engine, etc."
    )

    # --- Execution ---
    status: Mapped[str] = mapped_column(
        String(30), default="pending", index=True, comment="pending, in_progress, completed, dismissed, expired"
    )
    action_payload: Mapped[Optional[dict]] = mapped_column(
        JSONB, default=dict, comment="Data needed to execute this action (API endpoint, params, etc.)"
    )
    result: Mapped[Optional[dict]] = mapped_column(JSONB, default=dict, comment="Outcome after action was taken")
    completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    completed_by: Mapped[Optional[str]] = mapped_column(String(255))

    # --- Outcome ---
    outcome_score: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
        comment="Post-execution outcome: >0 = positive impact, <0 = negative, NULL = not yet measured",
    )
    was_auto_approved: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        comment="True if this action was auto-promoted from assisted to autonomous via brand_autonomy_grants",
    )

    # --- Expiry ---
    expires_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), comment="Auto-expire stale actions")

    __table_args__ = (
        Index("ix_operator_actions_pending", "status", "priority"),
        Index("ix_operator_actions_org_status", "organization_id", "status"),
    )


class SystemHealthSnapshot(Base):
    """Periodic health snapshot — consumed by the control layer.

    Written every few minutes by a health-check worker. Gives the dashboard
    real-time system state without expensive aggregation queries on every page load.
    """

    __tablename__ = "system_health_snapshots"

    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organizations.id"), nullable=False, index=True
    )

    # --- Counts ---
    total_brands: Mapped[int] = mapped_column(Integer, default=0)
    total_accounts: Mapped[int] = mapped_column(Integer, default=0)
    total_offers: Mapped[int] = mapped_column(Integer, default=0)
    total_content_items: Mapped[int] = mapped_column(Integer, default=0)

    # --- Content Pipeline State ---
    content_draft: Mapped[int] = mapped_column(Integer, default=0)
    content_generating: Mapped[int] = mapped_column(Integer, default=0)
    content_review: Mapped[int] = mapped_column(Integer, default=0)
    content_approved: Mapped[int] = mapped_column(Integer, default=0)
    content_publishing: Mapped[int] = mapped_column(Integer, default=0)
    content_published: Mapped[int] = mapped_column(Integer, default=0)
    content_failed: Mapped[int] = mapped_column(Integer, default=0)

    # --- Job State ---
    jobs_pending: Mapped[int] = mapped_column(Integer, default=0)
    jobs_running: Mapped[int] = mapped_column(Integer, default=0)
    jobs_completed_24h: Mapped[int] = mapped_column(Integer, default=0)
    jobs_failed_24h: Mapped[int] = mapped_column(Integer, default=0)
    jobs_retrying: Mapped[int] = mapped_column(Integer, default=0)

    # --- Actions ---
    actions_pending: Mapped[int] = mapped_column(Integer, default=0)
    actions_critical: Mapped[int] = mapped_column(Integer, default=0)
    actions_completed_24h: Mapped[int] = mapped_column(Integer, default=0)

    # --- Blockers ---
    active_blockers: Mapped[int] = mapped_column(Integer, default=0)
    active_alerts: Mapped[int] = mapped_column(Integer, default=0)

    # --- Revenue ---
    total_revenue_30d: Mapped[float] = mapped_column(Float, default=0.0)
    total_cost_30d: Mapped[float] = mapped_column(Float, default=0.0)

    # --- Provider Health ---
    providers_healthy: Mapped[int] = mapped_column(Integer, default=0)
    providers_degraded: Mapped[int] = mapped_column(Integer, default=0)
    providers_down: Mapped[int] = mapped_column(Integer, default=0)

    # --- Raw Detail ---
    details: Mapped[Optional[dict]] = mapped_column(JSONB, default=dict)

    __table_args__ = (Index("ix_health_snapshots_org_created", "organization_id", "created_at"),)
