"""add_cascade_delete_provider_profiles

Revision ID: e95d8f95a89e
Revises: 364023ff491f
Create Date: 2026-03-28 07:39:01.918098
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e95d8f95a89e'
down_revision: Union[str, None] = '364023ff491f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('avatar_provider_profiles_avatar_id_fkey', 'avatar_provider_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'avatar_provider_profiles', 'avatars', ['avatar_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('voice_provider_profiles_avatar_id_fkey', 'voice_provider_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'voice_provider_profiles', 'avatars', ['avatar_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voice_provider_profiles', type_='foreignkey')
    op.create_foreign_key('voice_provider_profiles_avatar_id_fkey', 'voice_provider_profiles', 'avatars', ['avatar_id'], ['id'])
    op.drop_constraint(None, 'avatar_provider_profiles', type_='foreignkey')
    op.create_foreign_key('avatar_provider_profiles_avatar_id_fkey', 'avatar_provider_profiles', 'avatars', ['avatar_id'], ['id'])
    # ### end Alembic commands ###
