"""Elite Affiliate Intelligence tables.

Revision ID: af_001
Revises: lpc_001
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

revision: str = "af_001"
down_revision: Union[str, None] = "lpc_001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table("af_network_accounts", sa.Column("id", sa.UUID(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("brand_id", sa.UUID(), nullable=False), sa.Column("network_name", sa.String(120), nullable=False), sa.Column("account_id_external", sa.String(255), nullable=True), sa.Column("api_key_env", sa.String(120), nullable=True), sa.Column("status", sa.String(30), server_default="active"), sa.Column("is_active", sa.Boolean(), server_default=sa.text("true")), sa.ForeignKeyConstraint(["brand_id"], ["brands.id"]), sa.PrimaryKeyConstraint("id"))

    op.create_table("af_merchants", sa.Column("id", sa.UUID(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("brand_id", sa.UUID(), nullable=False), sa.Column("network_id", sa.UUID(), nullable=True), sa.Column("merchant_name", sa.String(255), nullable=False), sa.Column("merchant_category", sa.String(120), nullable=True), sa.Column("trust_score", sa.Float(), server_default="0.5"), sa.Column("is_active", sa.Boolean(), server_default=sa.text("true")), sa.ForeignKeyConstraint(["brand_id"], ["brands.id"]), sa.ForeignKeyConstraint(["network_id"], ["af_network_accounts.id"]), sa.PrimaryKeyConstraint("id"))

    op.create_table("af_offers", sa.Column("id", sa.UUID(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("brand_id", sa.UUID(), nullable=False), sa.Column("merchant_id", sa.UUID(), nullable=True), sa.Column("offer_id_internal", sa.UUID(), nullable=True), sa.Column("product_name", sa.String(500), nullable=False), sa.Column("product_category", sa.String(120), nullable=True), sa.Column("offer_type", sa.String(60), server_default="affiliate"), sa.Column("destination_url", sa.String(1000), nullable=True), sa.Column("affiliate_url", sa.String(1000), nullable=True), sa.Column("commission_type", sa.String(30), server_default="percentage"), sa.Column("commission_rate", sa.Float(), server_default="0"), sa.Column("cookie_window_days", sa.Integer(), server_default="30"), sa.Column("epc", sa.Float(), server_default="0"), sa.Column("conversion_rate", sa.Float(), server_default="0"), sa.Column("refund_rate", sa.Float(), server_default="0"), sa.Column("trust_score", sa.Float(), server_default="0.5"), sa.Column("content_fit_score", sa.Float(), server_default="0.5"), sa.Column("platform_fit_score", sa.Float(), server_default="0.5"), sa.Column("audience_fit_score", sa.Float(), server_default="0.5"), sa.Column("rank_score", sa.Float(), server_default="0"), sa.Column("blocker_state", sa.String(60), nullable=True), sa.Column("truth_label", sa.String(40), server_default="configured"), sa.Column("is_active", sa.Boolean(), server_default=sa.text("true")), sa.ForeignKeyConstraint(["brand_id"], ["brands.id"]), sa.ForeignKeyConstraint(["merchant_id"], ["af_merchants.id"]), sa.ForeignKeyConstraint(["offer_id_internal"], ["offers.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_index("ix_afo_brand", "af_offers", ["brand_id"])

    op.create_table("af_links", sa.Column("id", sa.UUID(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("brand_id", sa.UUID(), nullable=False), sa.Column("offer_id", sa.UUID(), nullable=False), sa.Column("content_item_id", sa.UUID(), nullable=True), sa.Column("campaign_id", sa.UUID(), nullable=True), sa.Column("landing_page_id", sa.UUID(), nullable=True), sa.Column("platform", sa.String(50), nullable=True), sa.Column("account_id", sa.UUID(), nullable=True), sa.Column("full_url", sa.String(1500), nullable=False), sa.Column("short_url", sa.String(500), nullable=True), sa.Column("utm_params", JSONB(), server_default="{}"), sa.Column("disclosure_applied", sa.Boolean(), server_default=sa.text("false")), sa.Column("click_count", sa.Integer(), server_default="0"), sa.Column("conversion_count", sa.Integer(), server_default="0"), sa.Column("is_active", sa.Boolean(), server_default=sa.text("true")), sa.ForeignKeyConstraint(["brand_id"], ["brands.id"]), sa.ForeignKeyConstraint(["offer_id"], ["af_offers.id"]), sa.ForeignKeyConstraint(["content_item_id"], ["content_items.id"]), sa.PrimaryKeyConstraint("id"))

    op.create_table("af_clicks", sa.Column("id", sa.UUID(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("brand_id", sa.UUID(), nullable=False), sa.Column("link_id", sa.UUID(), nullable=False), sa.Column("clicked_at", sa.DateTime(timezone=True), nullable=True), sa.Column("referrer", sa.String(500), nullable=True), sa.Column("platform", sa.String(50), nullable=True), sa.ForeignKeyConstraint(["brand_id"], ["brands.id"]), sa.ForeignKeyConstraint(["link_id"], ["af_links.id"]), sa.PrimaryKeyConstraint("id"))

    op.create_table("af_conversions", sa.Column("id", sa.UUID(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("brand_id", sa.UUID(), nullable=False), sa.Column("link_id", sa.UUID(), nullable=False), sa.Column("offer_id", sa.UUID(), nullable=False), sa.Column("conversion_value", sa.Float(), server_default="0"), sa.Column("conversion_type", sa.String(40), server_default="sale"), sa.Column("converted_at", sa.DateTime(timezone=True), nullable=True), sa.ForeignKeyConstraint(["brand_id"], ["brands.id"]), sa.ForeignKeyConstraint(["link_id"], ["af_links.id"]), sa.ForeignKeyConstraint(["offer_id"], ["af_offers.id"]), sa.PrimaryKeyConstraint("id"))

    op.create_table("af_commissions", sa.Column("id", sa.UUID(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("brand_id", sa.UUID(), nullable=False), sa.Column("conversion_id", sa.UUID(), nullable=False), sa.Column("commission_amount", sa.Float(), server_default="0"), sa.Column("commission_status", sa.String(30), server_default="pending"), sa.Column("is_active", sa.Boolean(), server_default=sa.text("true")), sa.ForeignKeyConstraint(["brand_id"], ["brands.id"]), sa.ForeignKeyConstraint(["conversion_id"], ["af_conversions.id"]), sa.PrimaryKeyConstraint("id"))

    op.create_table("af_payouts", sa.Column("id", sa.UUID(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("brand_id", sa.UUID(), nullable=False), sa.Column("network_id", sa.UUID(), nullable=True), sa.Column("payout_amount", sa.Float(), server_default="0"), sa.Column("payout_status", sa.String(30), server_default="pending"), sa.Column("period", sa.String(30), nullable=True), sa.Column("is_active", sa.Boolean(), server_default=sa.text("true")), sa.ForeignKeyConstraint(["brand_id"], ["brands.id"]), sa.ForeignKeyConstraint(["network_id"], ["af_network_accounts.id"]), sa.PrimaryKeyConstraint("id"))

    op.create_table("af_blockers", sa.Column("id", sa.UUID(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("brand_id", sa.UUID(), nullable=False), sa.Column("offer_id", sa.UUID(), nullable=True), sa.Column("blocker_type", sa.String(60), nullable=False), sa.Column("description", sa.Text(), nullable=False), sa.Column("severity", sa.String(20), server_default="high"), sa.Column("is_active", sa.Boolean(), server_default=sa.text("true")), sa.ForeignKeyConstraint(["brand_id"], ["brands.id"]), sa.ForeignKeyConstraint(["offer_id"], ["af_offers.id"]), sa.PrimaryKeyConstraint("id"))

    op.create_table("af_disclosures", sa.Column("id", sa.UUID(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("brand_id", sa.UUID(), nullable=False), sa.Column("disclosure_type", sa.String(60), nullable=False), sa.Column("disclosure_text", sa.Text(), nullable=False), sa.Column("platform", sa.String(50), nullable=True), sa.Column("is_default", sa.Boolean(), server_default=sa.text("false")), sa.Column("is_active", sa.Boolean(), server_default=sa.text("true")), sa.ForeignKeyConstraint(["brand_id"], ["brands.id"]), sa.PrimaryKeyConstraint("id"))

    op.create_table("af_leaks", sa.Column("id", sa.UUID(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("brand_id", sa.UUID(), nullable=False), sa.Column("offer_id", sa.UUID(), nullable=True), sa.Column("link_id", sa.UUID(), nullable=True), sa.Column("leak_type", sa.String(60), nullable=False), sa.Column("severity", sa.String(20), server_default="medium"), sa.Column("revenue_loss_estimate", sa.Float(), server_default="0"), sa.Column("recommendation", sa.Text(), nullable=False), sa.Column("explanation", sa.Text(), nullable=True), sa.Column("is_active", sa.Boolean(), server_default=sa.text("true")), sa.ForeignKeyConstraint(["brand_id"], ["brands.id"]), sa.ForeignKeyConstraint(["offer_id"], ["af_offers.id"]), sa.ForeignKeyConstraint(["link_id"], ["af_links.id"]), sa.PrimaryKeyConstraint("id"))


def downgrade() -> None:
    for t in ("af_leaks", "af_disclosures", "af_blockers", "af_payouts", "af_commissions", "af_conversions", "af_clicks", "af_links", "af_offers", "af_merchants", "af_network_accounts"):
        op.drop_table(t)
