"""Event Bus — The horizontal integration layer.

This service is the single point of integration between all system layers.
When anything meaningful happens (state change, job completion, failure, etc.),
it emits a SystemEvent through this bus. Other layers consume these events
to stay coordinated.

Usage:
    from apps.api.services.event_bus import emit_event, emit_action

    # Emit a state change event
    await emit_event(
        db=db,
        domain="content",
        event_type="content.state_changed",
        entity_type="content_item",
        entity_id=item.id,
        previous_state="draft",
        new_state="generating",
        summary="Content item started generation",
        brand_id=item.brand_id,
        org_id=org_id,
    )

    # Create an operator action
    await emit_action(
        db=db,
        org_id=org_id,
        action_type="approve_content",
        title="Review content: How to Start a Business",
        category="approval",
        priority="medium",
        entity_type="content_item",
        entity_id=item.id,
        brand_id=item.brand_id,
    )
"""
import uuid
from datetime import datetime, timezone
from typing import Optional

import structlog
from sqlalchemy.ext.asyncio import AsyncSession

from packages.db.models.system_events import OperatorAction, SystemEvent

logger = structlog.get_logger()


async def emit_event(
    db: AsyncSession,
    *,
    domain: str,
    event_type: str,
    summary: str,
    org_id: Optional[uuid.UUID] = None,
    brand_id: Optional[uuid.UUID] = None,
    entity_type: Optional[str] = None,
    entity_id: Optional[uuid.UUID] = None,
    previous_state: Optional[str] = None,
    new_state: Optional[str] = None,
    severity: str = "info",
    actor_type: str = "system",
    actor_id: Optional[str] = None,
    details: Optional[dict] = None,
    correlation_id: Optional[uuid.UUID] = None,
    parent_event_id: Optional[uuid.UUID] = None,
    requires_action: bool = False,
) -> SystemEvent:
    """Emit a system event — the primary integration mechanism.

    This is a lightweight, non-blocking write. Events are consumed
    asynchronously by the control layer, intelligence layer, and
    recovery layer.
    """
    event = SystemEvent(
        organization_id=org_id,
        brand_id=brand_id,
        event_domain=domain,
        event_type=event_type,
        event_severity=severity,
        entity_type=entity_type,
        entity_id=entity_id,
        previous_state=previous_state,
        new_state=new_state,
        actor_type=actor_type,
        actor_id=actor_id,
        summary=summary,
        details=details or {},
        correlation_id=correlation_id,
        parent_event_id=parent_event_id,
        requires_action=requires_action,
    )
    db.add(event)
    await db.flush()

    logger.info(
        "system_event.emitted",
        domain=domain,
        event_type=event_type,
        entity_type=entity_type,
        entity_id=str(entity_id) if entity_id else None,
        severity=severity,
        requires_action=requires_action,
    )

    return event


async def emit_action(
    db: AsyncSession,
    *,
    org_id: uuid.UUID,
    action_type: str,
    title: str,
    category: str,
    priority: str = "medium",
    brand_id: Optional[uuid.UUID] = None,
    description: Optional[str] = None,
    entity_type: Optional[str] = None,
    entity_id: Optional[uuid.UUID] = None,
    source_event_id: Optional[uuid.UUID] = None,
    source_module: Optional[str] = None,
    action_payload: Optional[dict] = None,
    expires_at: Optional[datetime] = None,
) -> OperatorAction:
    """Create an operator action — surfaces in the control layer.

    Actions represent things that need human attention or approval.
    They are generated by various system layers and consumed by the
    dashboard control surface.
    """
    action = OperatorAction(
        organization_id=org_id,
        brand_id=brand_id,
        action_type=action_type,
        title=title,
        description=description,
        priority=priority,
        category=category,
        entity_type=entity_type,
        entity_id=entity_id,
        source_event_id=source_event_id,
        source_module=source_module,
        status="pending",
        action_payload=action_payload or {},
        expires_at=expires_at,
    )
    db.add(action)
    await db.flush()

    logger.info(
        "operator_action.created",
        action_type=action_type,
        category=category,
        priority=priority,
        entity_type=entity_type,
    )

    return action


async def complete_action(
    db: AsyncSession,
    action: OperatorAction,
    *,
    completed_by: str = "system",
    result: Optional[dict] = None,
) -> OperatorAction:
    """Mark an operator action as completed."""
    action.status = "completed"
    action.completed_at = datetime.now(timezone.utc)
    action.completed_by = completed_by
    action.result = result or {}
    await db.flush()

    logger.info(
        "operator_action.completed",
        action_id=str(action.id),
        action_type=action.action_type,
        completed_by=completed_by,
    )

    return action


async def dismiss_action(
    db: AsyncSession,
    action: OperatorAction,
    *,
    dismissed_by: str = "operator",
) -> OperatorAction:
    """Dismiss an operator action."""
    action.status = "dismissed"
    action.completed_at = datetime.now(timezone.utc)
    action.completed_by = dismissed_by
    await db.flush()
    return action


def emit_event_sync(
    session,
    *,
    domain: str,
    event_type: str,
    summary: str,
    org_id=None,
    brand_id=None,
    entity_type=None,
    entity_id=None,
    previous_state=None,
    new_state=None,
    severity="info",
    actor_type="system",
    actor_id=None,
    details=None,
    correlation_id=None,
    requires_action=False,
) -> SystemEvent:
    """Synchronous version for use in Celery workers (sync SQLAlchemy sessions)."""
    event = SystemEvent(
        organization_id=org_id,
        brand_id=brand_id,
        event_domain=domain,
        event_type=event_type,
        event_severity=severity,
        entity_type=entity_type,
        entity_id=entity_id,
        previous_state=previous_state,
        new_state=new_state,
        actor_type=actor_type,
        actor_id=actor_id,
        summary=summary,
        details=details or {},
        correlation_id=correlation_id,
        requires_action=requires_action,
    )
    session.add(event)
    session.flush()

    logger.info(
        "system_event.emitted_sync",
        domain=domain,
        event_type=event_type,
        entity_type=entity_type,
        severity=severity,
    )

    return event
